# This script generates the uri lists of hosts, that does not have any Server Profile associated with them. (Available Targets)
#
# @author Mustafa Yıldırım

import requests
import json
import urllib3
urllib3.disable_warnings() #With this statement, SSL warnings that is being received everytime the script is run is ignored.

#==========================================Variables that needs to be edited accordingly your environment==========================================================
oneviewip="10.X.X.X"#Oneview IP Address 
auth_token='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' #Authenticatin token that is generated by "getAuthToken.py" in this repo or via POST login-sessions API call
url = f"https://{oneviewip}/rest/server-profiles/available-targets"

payload={}
headers = {
  'Auth': auth_token,
  'X-Api-Version': '3000', #oneview version 6.30 --> 'x-api-key': '3200' 6.20 -->'x-api-key': '3000'
  'Content-Type': 'application/json'
}


response = requests.request("GET", url, headers=headers, data=payload,verify=False)

hw_uri_and_name={}
for i in response.json()['targets']:
  print(i['serverHardwareUri'],i['serverHardwareName'])
  hw_uri_and_name[i['serverHardwareName']]=i['serverHardwareUri']
  
#print(response.text)
print(hw_uri_and_name)
print("Script is done.")